#!/bin/bash
APP_EXE_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$APP_EXE_DIR/../../.." && pwd)"

osascript <<APPLESCRIPT
tell application "Terminal"
  activate
  do script quoted form of "$PROJECT_DIR/VIDZDOWNLOAD.command"
end tell
APPLESCRIPT
